[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "app.js"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' blob: https://api.mapbox.com https://unpkg.com https://cdnjs.cloudflare.com https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://api.mapbox.com https://fonts.googleapis.com; img-src 'self' data: blob: https://api.mapbox.com https://*.mapbox.com https://www.google-analytics.com https://georide.milanwebportal.com; connect-src 'self' https://api.mapbox.com https://events.mapbox.com https://*.mapbox.com https://www.google-analytics.com https://*.google-analytics.com https://region1.google-analytics.com wss://broker.hivemq.com:8884 wss://broker.hivemq.com; font-src 'self' data: https://fonts.gstatic.com; worker-src 'self' blob:; object-src 'none';"

[[redirects]]
  from = "/play"
  to = "/play.html"
  status = 200
